version: '3'
volumes:
  postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
    secrets:
      - db_username
      - db_password
    depends_on:
      - db
  db:
    environment:
# From https://hub.docker.com/_/postgres | Docker Secrets:
      POSTGRES_USER_FILE: /run/secrets/db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_username
      - db_password
  web:
    build:
      context: .
      dockerfile: ./docker/web/DockerFile
    depends_on:
      - app
    ports:
      - 8080:80
secrets:
    db_password:
      file: ./secrets/database_password.txt
    db_username:
      file: ./secrets/database_username.txt