# Base image:
FROM nginx

# Install dependencies
RUN apt-get update -qq && apt-get -y install apache2-utils iputils-ping

# establish where Nginx should look for files
ENV FRONTEND_ROOT /var/www/frontend

# Set our working directory inside the image
WORKDIR $FRONTEND_ROOT

# create log directory
RUN mkdir log

# copy over static assets
COPY frontend/public public/

# Copy Nginx config template
COPY docker/web/nginx.conf /tmp/docker.nginx

# substitute variable references in the Nginx config template for real values from the environment
# put the final config in its place
RUN envsubst '$FRONTEND_ROOT' < /tmp/docker.nginx > /etc/nginx/conf.d/default.conf

EXPOSE 80

# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
CMD [ "nginx", "-g", "daemon off;" ]